### ISSUE TITLE
Package cannot be found on Pypi

### ISSUE THREAD

**Issue by WouterVH** [lameiro/cx_oracle_on_ctypes#11]
Let's make a release and upload the package to Pypi.
I can help with that.

**Comment by WouterVH** [comment]
see #12

**Comment by lameiro** [comment]
Thanks for the contribution Wouter!
Your PR #12 is now merged and the package released on PyPI.

**Comment by WouterVH** [comment]
I think the package-upload to pypi failed

I see a page https://pypi.python.org/pypi/cx_oracle_on_ctypes/
but no tarball to download

**Comment by lameiro** [comment]
Erm, indeed.
Fixed now.
