### ISSUE TITLE
Descriprtion is truncated if it contains zero byte

### ISSUE THREAD

**Issue by K0Te** [lameiro/cx_oracle_on_ctypes#13]
Hi,

There is difference between stock cx_Oracle and cx_oracle_on_ctypes for $subj.
cx_Oracle:
```
>>> cu.execute("""SELECT 'Test\0NameForDesc' from dual""").description
[("'TEST\x00NAMEFORDESC'", <type 'cx_Oracle.FIXED_CHAR'>, 16, 16, 0, 0, 1)]
```

cx_oracle_on_ctypes:
```
>>>> cu.execute("""SELECT 'Test\0NameForDesc' from dual""").description
[("'TEST", <class 'cx_Oracle.stringvar.FIXED_CHAR'>, 16, 16, 0, 0, 1)]
```

**Comment by K0Te** [comment]
It seems that it's due to following lines in cursor.py:
```python
c_name = ctypes.c_char_p()
...
name = c_name.value[:c_name_length.value] # doesn't it give back a NULL terminated string?!
```
name gets truncated during execution of "value" getter, so it can't be sliced according to it's real length.

**Comment by lameiro** [comment]
Thanks K0Te, the problem was exactly where you pointed. This is fixed now.
