### ISSUE TITLE
Compatibility with oracle 12

### ISSUE THREAD

**Issue by mboscolo** [lameiro/cx_oracle_on_ctypes#4]
I test this module on:
Debian 8 
[PyPy 2.4.0 with GCC 4.9.2] on linux2
Oracle 12 as client.
But it seems only to be compatible only with oracle 11 -10 ..
Do you think you will support oracle 12 very soon.. or in any way can you point me out how to make it work on oracle 12 ? 
In case i fix it I will pull the code in case I succed

regards,
Matteo

**Comment by lameiro** [comment]
Hi Matteo,
I just commited some initial support. It doesn't implement the new features yet, just allows you to use the Oracle 12 libs. Let me know if you still have issues.
